### ISSUE TITLE
Moving of end marker in example fails

### ISSUE THREAD

**Issue by florianf** [tkrajina/leaflet-editable-polyline#11]
Hi,
when I try to move one of the endmarkes (the one farthest in the west) int the http://tkrajina.github.io/leaflet-editable-polyline/example1.html I get an error (Tested in latest Chrome & Firefox):

Chrome error:
Uncaught TypeError: 
Cannot read property 'getLatLng' of undefinedleaflet-editable-polyline.js:222 (anonymous function)
leaflet.js:6 o.Mixin.Events.fireEvent
leaflet.js:9 o.Handler.MarkerDrag.o.Handler.extend._onDragStart
leaflet.js:6 o.Mixin.Events.fireEventleaflet.js:8 o.Draggable.o.Class.extend._onMove
leaflet.js:8 t.(anonymous function).s

Firefox error:
TypeError: that._markers[(pointNo - 1)] is undefined

Also: 
When I move the other end marker first and then try to add a new point (click on moved end marker), the previous point is duplicated and no helper line is shown for adding a new point.

Thx.

**Comment by tkrajina** [comment]
I'm trying with the latest version of Firefox and I can't reproduce it. But the example in the link was with the earlier version of the code. I upgraded it now with the latest master, can you try if you still get the same error?

**Comment by florianf** [comment]
I tried with todays master, it works now.

Thx for your efforts, it's really appreciated!
