### ISSUE TITLE
Lat/Lon vs Lon/Lat

### ISSUE THREAD

**Issue by thomersch** [tkrajina/leaflet-editable-polyline#6]
Hey there,

first of all: Thanks for your work, that's really a nice plugin - I already love it. Though I have a little issue: L.Polyline.PolylineEditor takes pairs of LatLon while L.Polyline from Leaflet itself wants to receive LonLat pairs, which is a bit confusing, especially because GeoJSON is LonLat as well.
What do you think? Would it be okay to do that the other way around?

Thomas

**Comment by stihlsicher** [comment]
Hi tk,

just had the same issue as Thomas. I've got a WKT, which is imported by the omnivore plugin. Grabbing the coordinates from the resulting Layer, results in an editable polyline, which is located right in the middle of the sea. All work fine after exchanging lat and lon. It took me some time to figure out the problem.

tj

**Comment by tkrajina** [comment]
I will close this issue. because I don't think this needs to be fixed here. This plugin is just a tiny layer about Leaflet's polyline. If you think something is wrong with the way Leaflet polyline deals with points -- it has to fixed there.
